---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(levelname)s:[in %(pathname)s:%(lineno)d] - %(message)s"

handlers:
  # CONSOLE LOGGER HAS TO BE THE FIRST ONE - DO NOT RE-ORDER!
  console:
    class: logging.StreamHandler
    level: TRACE
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  urllib3.connectionpool:
    level: ERROR
  py_free_proxy:
    level: DEBUG

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]
